runtime: nodejs12

env_variables:
  PGHOST: '35.235.75.81'
  PGUSER: 'postgres'
  PGDATABASE: 'cofu'
  PGPASSWORD: '4q1Bx4M1EC53cyb7'
  PGPORT: 5432
  IPBIND: '0.0.0.0'
  REDISHOST: '10.18.97.75'

vpc_access_connector:
  name: projects/cofu-305406/locations/us-west2/connectors/cofu-sessions-connector
